# Generated by Django 2.0.7 on 2018-07-02 22:52

from django.db import migrations, models
import django.db.models.deletion
import for_runners.models.gpx


class Migration(migrations.Migration):

    dependencies = [
        ('for_runners', '0001_squashed_0011_auto_20180702_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='for_runners.DisciplineModel'),
        ),
        migrations.AlterField(
            model_name='gpxmodel',
            name='gpx',
            field=models.FileField(upload_to=for_runners.models.gpx.upload_path, verbose_name='GPX Track'),
        ),
        migrations.AlterField(
            model_name='gpxmodel',
            name='track_svg',
            field=models.FileField(blank=True, null=True, upload_to=for_runners.models.gpx.upload_path, verbose_name='Track SVG'),
        ),
    ]
