# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-02 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_runners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxmodel',
            name='heart_rate_avg',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Average heart rate.', null=True),
        ),
        migrations.AddField(
            model_name='gpxmodel',
            name='heart_rate_max',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Maximum heart rate.', null=True),
        ),
        migrations.AddField(
            model_name='gpxmodel',
            name='heart_rate_min',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Minimum heart rate.', null=True),
        ),
    ]
