# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('for_runners', '0002_auto_20180602_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLinkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Create time')),
                ('lastupdatetime', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Time of the last change.')),
                ('url', models.URLField(help_text='Link URL')),
                ('text', models.CharField(blank=True, help_text='Link text (leave empty to generate it from url)', max_length=127, null=True)),
                ('title', models.CharField(blank=True, help_text='Link title (leave empty to generate it from url)', max_length=127, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='eventmodel',
            options={'ordering': ('-start_time', '-pk'), 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterField(
            model_name='gpxmodel',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='for_runners.EventModel'),
        ),
        migrations.AddField(
            model_name='eventlinkmodel',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='for_runners.EventModel'),
        ),
    ]
