# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_runners', '0003_auto_20180612_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxmodel',
            name='finish_temperature',
            field=models.FloatField(blank=True, help_text='Temperature at finish.', null=True),
        ),
        migrations.AddField(
            model_name='gpxmodel',
            name='finish_weather_state',
            field=models.CharField(blank=True, help_text='Weather state at finish.', max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='gpxmodel',
            name='start_temperature',
            field=models.FloatField(blank=True, help_text='Temperature at start.', null=True),
        ),
        migrations.AddField(
            model_name='gpxmodel',
            name='start_weather_state',
            field=models.CharField(blank=True, help_text='Weather state at start.', max_length=127, null=True),
        ),
    ]
