# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_runners', '0004_auto_20180621_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxmodel',
            name='creator',
            field=models.CharField(
                blank=True, help_text='Used device to create this track', max_length=511, null=True
            ),
        ),
    ]
