# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('for_runners', '0005_gpxmodel_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpxmodel',
            name='map_image',
        ),
    ]
