# Generated by Django 2.1.4 on 2018-12-17 16:19

from django.db import migrations, models

# https://github.com/jedie/django-for-runners
import for_runners.models.gpx


class Migration(migrations.Migration):

    dependencies = [("for_runners", "0006_auto_20180902_1958")]

    operations = [
        migrations.AddField(
            model_name="gpxmodel",
            name="gpx_file",
            field=models.FileField(
                blank=True,
                max_length=511,
                null=True,
                upload_to=for_runners.models.gpx.gpx_upload_path,
                verbose_name="GPX Track",
            ),
        )
    ]
