# Generated by Django 2.1.1 on 2018-09-16 14:05

from django.db import migrations
import for_runners.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('for_runners', '0006_auto_20180902_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxmodel',
            name='gpx_file',
            field=for_runners.models.fields.GpxFileField(blank=True, null=True, upload_to=for_runners.models.fields.gpx_upload_to, verbose_name='GPX Track'),
        ),
    ]
