# Generated by Django 2.1.4 on 2018-12-17 16:19
from django.db import migrations, models

# https://github.com/jedie/django-tools
import django_tools

# https://github.com/jedie/django-for-runners
import for_runners.models.gpx


class Migration(migrations.Migration):

    dependencies = [("for_runners", "0006_auto_20180902_1958")]

    operations = [
        migrations.AddField(
            model_name="gpxmodel",
            name="gpx_file",
            field=models.FileField(
                blank=True,
                max_length=511,
                null=True,
                storage=django_tools.file_storage.file_system_storage.OverwriteFileSystemStorage(create_backups=True),
                upload_to=for_runners.models.gpx.gpx_upload_path,
                verbose_name="GPX Track",
            ),
        ),
        migrations.AlterField(
            model_name="gpxmodel",
            name="track_svg",
            field=models.FileField(
                verbose_name="Track SVG",
                upload_to=for_runners.models.gpx.svg_upload_path,
                storage=django_tools.file_storage.file_system_storage.OverwriteFileSystemStorage(create_backups=False),
                null=True,
                blank=True,
            ),
        ),
    ]
