# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_runners', '0007_create_distance_model_20180627_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='no',
            field=models.PositiveIntegerField(blank=True, help_text='Sequential number of the event', null=True),
        ),
    ]
