# Generated by Django 2.1.4 on 2018-12-17 16:19
import io

from django.db import migrations, models

# https://github.com/jedie/django-for-runners
from for_runners.services.gpx import generate_svg


def forwards(apps, schema_editor):
    # GpxModel = apps.get_model("for_runners", "GpxModel")
    from for_runners.models import GpxModel

    qs = GpxModel.objects.all()
    total_count = qs.count()
    for no, instance in enumerate(qs):
        print("[%i/%i] Generate SVG for: %s" % (no, total_count, instance))

        if not instance.gpx:
            continue

        gpx_data = io.StringIO(instance.gpx)
        instance.gpx_file.save(
            name="temp.gpx",  # real file path will be set in for_runners.models.gpx.GpxModel#gpx_upload_path
            content=gpx_data,
            save=False,
        )
        generate_svg(gpx_track=instance, force=True)

        instance.save()


class Migration(migrations.Migration):

    dependencies = [("for_runners", "0007_gpxmodel_gpx_file")]

    operations = [migrations.RunPython(forwards, migrations.RunPython.noop)]
