# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_runners', '0008_auto_20180628_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxmodel',
            name='net_duration',
            field=models.TimeField(blank=True, help_text='The officially measured time (e.g. from the official timekeeping of a running event.)', null=True, verbose_name='Net Duration'),
        ),
    ]
