# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_runners', '0009_gpxmodel_net_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventmodel',
            options={'ordering': ('-start_date', '-pk'), 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='start_time',
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start date of the run', null=True),
        ),
    ]
