# Generated by Django 3.2.15 on 2022-08-30 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('for_runners', '0009_auto_20190402_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participationmodel',
            options={
                'ordering': ('-event__start_date', 'user'),
                'verbose_name': 'Event Participation',
                'verbose_name_plural': 'Event Participations',
            },
        ),
        migrations.RenameField(
            model_name='participationmodel',
            old_name='person',
            new_name='user',
        ),
    ]
