# Generated by Django 4.1.6 on 2023-02-09 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("for_runners", "0012_participationimagemodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventmodel",
            name="createby",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User how create this entry.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_createby",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="eventmodel",
            name="lastupdateby",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User as last edit this entry.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_lastupdateby",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="gpxmodel",
            name="lastupdateby",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="User as last edit this entry",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_lastupdateby",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="gpxmodel",
            name="tracked_by",
            field=models.ForeignKey(
                editable=False,
                help_text="The user that tracked this gpx entry",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_createby",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
