

name: tests

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 8 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.11"]
    steps:
    - name: Checkout
      run: |
        echo $GITHUB_REF $GITHUB_SHA
        git clone https://github.com/$GITHUB_REPOSITORY.git .
        git fetch origin $GITHUB_SHA:temporary-ci-branch
        git checkout $GITHUB_SHA || (git fetch && git checkout $GITHUB_SHA)

    - name: 'Set up Python ${{ matrix.python-version }}'
      uses: actions/setup-python@v5
      # https://github.com/marketplace/actions/setup-python
      with:
        python-version: '${{ matrix.python-version }}'
        cache: 'pip' # caching pip dependencies
        cache-dependency-path: '**/requirements.*.txt'

    - name: 'Bootstrap'
      # The first manage.py call will create the .venv
      run: |
        ./manage.py version

    - name: 'Display all Django commands'
      run: |
        ./manage.py --help

    - name: 'Run pip-audit'
      run: |
        ./manage.py pip_audit

    - name: 'Run tests with Python v${{ matrix.python-version }}'
      env:
        PYTHONUNBUFFERED: 1
        PYTHONWARNINGS: always
      run: |
        ./manage.py coverage

    - name: 'Upload coverage report'
      uses: codecov/codecov-action@v4
      # https://github.com/marketplace/actions/codecov
      with:
        fail_ci_if_error: false
        verbose: true

